### ISSUE TITLE
Anvil RAAS v2 and v4 broken

### ISSUE THREAD

**Issue by ajesina** [w4rum/squadlanes#37] opened 2022-06-28 20:53 UTC
Clicking either main base in Anvril RAAS v2 and v4 layers does not reveal any flags right now.

**Comment by w4rum** [comment] 2022-07-04 15:42
Sorry for the delayed response. I can confirm the issue on my end but can't intuitively see the cause, so I'll have to properly debug this.

Unfortunately I'm super busy the next couple of days, so don't expect an immediate fix for this.

**Comment by w4rum** [comment] 2022-07-12 09:42
Fixed in c2e50563db092051c41fcbd9466a1f3710080650.

Thanks for the report.

**Closed by w4rum** 2022-07-12 09:42 UTC
Labels: bug, map ui
