### ISSUE TITLE
Are there maps extracted by Squad V6.0.1? I can't execute the extract script

### ISSUE THREAD

**Issue by Ccptsoap** [w4rum/squadlanes#56] opened 2023-11-06 16:00 UTC
![1699286400757](https://github.com/w4rum/squadlanes/assets/34964250/8b4f6f4f-e600-40c0-84a4-423ba111c490)

**Comment by w4rum** [comment] 2023-12-29 07:49
closing because it's obsolete and can't reproduce

**Closed by w4rum** 2023-12-29 07:49 UTC
